name: Build Bug
description: Use template to submit a Build Bug
title: "[Build]: "
labels: ["Build"]
assignees:
  - cqian2
body:
- type: checkboxes
  attributes:
    label: Is there an existing issue for this?
    description: Please search to see if an issue already exists for the bug you encountered.
    options:
    - label: I have searched the existing issues
      required: true
- type: textarea
  attributes:
    label: What happened?
    description: Please provide reproduce steps and sample cmdline if possible which help us to debug it.
    placeholder: |
      1. In Linux or Browser or Applications...
      2. With this config...
      3. Run '...'
      4. See error...
  validations:
    required: true
- type: textarea
  attributes:
    label: What impacted?
    description: Any program or milestone would be impacted if issue yet resolved? Please provide the information as detail as possible to help us understand and prioritize the issues.
  validations:
    required: false
- type: dropdown
  id: contribute
  attributes:
    label: Do you want to contribute a patch to fix the issue?
    multiple: false
    options:
      - Yes, I'm glad to submit a patch to fix it
      - No.
