name: Regression
description: Use template to submit a regression
title: "[Regression]: "
body:
- type: textarea
  attributes:
    label: Regression Isolation Status
    description: Please provide good and bad configuration for better isolation.
    placeholder: |
      1. Good libva/libva-utils/gmmlib/media-driver version...
      2. Bad libva/libva-utils/gmmlib/media-driver version...
      3. Test command...
      4. See error...
  validations:
    required: true
- type: dropdown
  id: usage
  attributes:
    label: What's the usage scenario when you are seeing the problem?
    multiple: true
    options:
      - Transcode for media delivery
      - Playback
      - Web browser
      - Cloud Gaming
      - Video Analytics
      - Video Conference
      - Immersive Media
      - Content Creation
      - Game Streaming
      - Others
- type: textarea
  attributes:
    label: What impacted?
    description: Any program or milestone would be impacted if issue yet resolved? Please provide the information as detail as possible to help us understand and prioritize the issues.
    placeholder: If you select "Others" for above usage, please describe your usage scenario here to help us understand the impact.
  validations:
    required: false